language: node_js
sudo: false
node_js:
  - stable
  - 8

before_deploy:
  - npm install --global surge
  - npm run build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: build
    on:
      branch: default
      node: stable
  - provider: surge
    skip-cleanup: true
    project: build
    domain: genie-explorer.aoe2.se
    on:
      branch: default
      node: stable
